//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractMSInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractMSInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="msIDType" default="MSISDN">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="MSISDN"/>
 *             &lt;enumeration value="MIN"/>
 *             &lt;enumeration value="IMSI"/>
 *             &lt;enumeration value="IMEI"/>
 *             &lt;enumeration value="MDN"/>
 *             &lt;enumeration value="EME_MSID"/>
 *             &lt;enumeration value="IPV4"/>
 *             &lt;enumeration value="IPV6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="msIDValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="encryption" default="ASC">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="ASC"/>
 *             &lt;enumeration value="B64"/>
 *             &lt;enumeration value="CRP"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractMSInformationType")
@XmlSeeAlso({
    OutputMSInformationType.class,
    InputMSInformationType.class
})
public class AbstractMSInformationType {

    @XmlAttribute(name = "msIDType")
    protected String msIDType;
    @XmlAttribute(name = "msIDValue")
    protected String msIDValue;
    @XmlAttribute(name = "encryption")
    protected String encryption;

    /**
     * Gets the value of the msIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsIDType() {
        if (msIDType == null) {
            return "MSISDN";
        } else {
            return msIDType;
        }
    }

    /**
     * Sets the value of the msIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsIDType(String value) {
        this.msIDType = value;
    }

    /**
     * Gets the value of the msIDValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsIDValue() {
        return msIDValue;
    }

    /**
     * Sets the value of the msIDValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsIDValue(String value) {
        this.msIDValue = value;
    }

    /**
     * Gets the value of the encryption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryption() {
        if (encryption == null) {
            return "ASC";
        } else {
            return encryption;
        }
    }

    /**
     * Sets the value of the encryption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryption(String value) {
        this.encryption = value;
    }

}
