//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Abstract type representing the response information returned from a service request.
 * 
 * <p>Java class for AbstractResponseParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractResponseParametersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractResponseParametersType")
@XmlSeeAlso({
    DetermineRouteResponseTypeNav.class,
    GetPositionResponseType.class,
    GetNearbyMapObjResponseType.class,
    ProcessCursorResponse.class,
    SetCursorPositionResponse.class,
    GetCursorPositionResponse.class,
    CursorFetchResponse.class,
    GetCursorInfoResponse.class,
    GetPortrayMapCapabilitiesResponseType.class,
    DirectoryResponseType.class,
    DetermineRouteResponseType.class,
    PortrayMapResponseType.class,
    ReverseGeocodeResponseType.class,
    SLIAType.class,
    GeocodeResponseType.class
})
public abstract class AbstractResponseParametersType {


}
