//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the list of areas, locations, and types of features in which the route should avoid passing through.
 * 
 * <p>Java class for AvoidListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvoidListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}AOI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/xls}_Location" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/xls}AvoidFeature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvoidListType", propOrder = {
    "aoi",
    "location",
    "avoidFeature"
})
public class AvoidListType {

    @XmlElement(name = "AOI")
    protected List<AreaOfInterestType> aoi;
    @XmlElementRef(name = "_Location", namespace = "http://www.opengis.net/xls", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractLocationType>> location;
    @XmlElement(name = "AvoidFeature")
    protected List<AvoidFeatureType> avoidFeature;

    /**
     * List of geographic areas to avoid.Gets the value of the aoi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aoi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAOI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreaOfInterestType }
     * 
     * 
     */
    public List<AreaOfInterestType> getAOI() {
        if (aoi == null) {
            aoi = new ArrayList<AreaOfInterestType>();
        }
        return this.aoi;
    }

    /**
     * List of locations to avoid.Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AbstractLocationType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractPOIType }{@code >}
     * {@link JAXBElement }{@code <}{@link PointOfInterestType }{@code >}
     * {@link JAXBElement }{@code <}{@link PositionType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractPositionType }{@code >}
     * {@link JAXBElement }{@code <}{@link AddressType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractLocationType>> getLocation() {
        if (location == null) {
            location = new ArrayList<JAXBElement<? extends AbstractLocationType>>();
        }
        return this.location;
    }

    /**
     * Gets the value of the avoidFeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidFeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AvoidFeatureType }
     * 
     * 
     */
    public List<AvoidFeatureType> getAvoidFeature() {
        if (avoidFeature == null) {
            avoidFeature = new ArrayList<AvoidFeatureType>();
        }
        return this.avoidFeature;
    }

}
