//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CenterContextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CenterContextType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CenterPoint" type="{http://www.opengis.net/gml}PointType"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="DisplayScale" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *             &lt;element name="DPI" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="Radius" type="{http://www.opengis.net/xls}RadiusType"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="azimuth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SRS" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CenterContextType", propOrder = {
    "centerPoint",
    "displayScale",
    "dpi",
    "radius"
})
public class CenterContextType {

    @XmlElement(name = "CenterPoint", required = true)
    protected PointType centerPoint;
    @XmlElement(name = "DisplayScale")
    protected BigInteger displayScale;
    @XmlElement(name = "DPI")
    protected BigInteger dpi;
    @XmlElement(name = "Radius")
    protected RadiusType radius;
    @XmlAttribute(name = "azimuth")
    protected BigInteger azimuth;
    @XmlAttribute(name = "SRS", required = true)
    protected String srs;

    /**
     * Gets the value of the centerPoint property.
     * 
     * @return
     *     possible object is
     *     {@link PointType }
     *     
     */
    public PointType getCenterPoint() {
        return centerPoint;
    }

    /**
     * Sets the value of the centerPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointType }
     *     
     */
    public void setCenterPoint(PointType value) {
        this.centerPoint = value;
    }

    /**
     * Gets the value of the displayScale property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDisplayScale() {
        return displayScale;
    }

    /**
     * Sets the value of the displayScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDisplayScale(BigInteger value) {
        this.displayScale = value;
    }

    /**
     * Gets the value of the dpi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDPI() {
        return dpi;
    }

    /**
     * Sets the value of the dpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDPI(BigInteger value) {
        this.dpi = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link RadiusType }
     *     
     */
    public RadiusType getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadiusType }
     *     
     */
    public void setRadius(RadiusType value) {
        this.radius = value;
    }

    /**
     * Gets the value of the azimuth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAzimuth() {
        return azimuth;
    }

    /**
     * Sets the value of the azimuth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAzimuth(BigInteger value) {
        this.azimuth = value;
    }

    /**
     * Gets the value of the srs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRS() {
        return srs;
    }

    /**
     * Sets the value of the srs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRS(String value) {
        this.srs = value;
    }

}
