//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorOriginEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CursorOriginEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CURRENT_POSITION"/>
 *     &lt;enumeration value="RESULT_SET_START"/>
 *     &lt;enumeration value="RESULT_SET_END"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CursorOriginEnum", namespace = "http://www.opengis.net/ols/nav")
@XmlEnum
public enum CursorOriginEnum {

    CURRENT_POSITION,
    RESULT_SET_START,
    RESULT_SET_END;

    public String value() {
        return name();
    }

    public static CursorOriginEnum fromValue(String v) {
        return valueOf(v);
    }

}
