//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CursorTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RouteLinkAndCostType"/>
 *     &lt;enumeration value="MapObjType"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CursorTypeEnum", namespace = "http://www.opengis.net/ols/nav")
@XmlEnum
public enum CursorTypeEnum {

    @XmlEnumValue("RouteLinkAndCostType")
    ROUTE_LINK_AND_COST_TYPE("RouteLinkAndCostType"),
    @XmlEnumValue("MapObjType")
    MAP_OBJ_TYPE("MapObjType");
    private final String value;

    CursorTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CursorTypeEnum fromValue(String v) {
        for (CursorTypeEnum c: CursorTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
