//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CursorInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CursorBufferStart" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="CursorBufferEnd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ResultsSetComplete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CurrentCursorPosition" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CursorInfoType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "cursorBufferStart",
    "cursorBufferEnd",
    "resultsSetComplete",
    "currentCursorPosition"
})
public class CursorInfoType {

    @XmlElement(name = "CursorBufferStart")
    protected long cursorBufferStart;
    @XmlElement(name = "CursorBufferEnd")
    protected long cursorBufferEnd;
    @XmlElement(name = "ResultsSetComplete")
    protected boolean resultsSetComplete;
    @XmlElement(name = "CurrentCursorPosition")
    protected long currentCursorPosition;

    /**
     * Gets the value of the cursorBufferStart property.
     * 
     */
    public long getCursorBufferStart() {
        return cursorBufferStart;
    }

    /**
     * Sets the value of the cursorBufferStart property.
     * 
     */
    public void setCursorBufferStart(long value) {
        this.cursorBufferStart = value;
    }

    /**
     * Gets the value of the cursorBufferEnd property.
     * 
     */
    public long getCursorBufferEnd() {
        return cursorBufferEnd;
    }

    /**
     * Sets the value of the cursorBufferEnd property.
     * 
     */
    public void setCursorBufferEnd(long value) {
        this.cursorBufferEnd = value;
    }

    /**
     * Gets the value of the resultsSetComplete property.
     * 
     */
    public boolean isResultsSetComplete() {
        return resultsSetComplete;
    }

    /**
     * Sets the value of the resultsSetComplete property.
     * 
     */
    public void setResultsSetComplete(boolean value) {
        this.resultsSetComplete = value;
    }

    /**
     * Gets the value of the currentCursorPosition property.
     * 
     */
    public long getCurrentCursorPosition() {
        return currentCursorPosition;
    }

    /**
     * Sets the value of the currentCursorPosition property.
     * 
     */
    public void setCurrentCursorPosition(long value) {
        this.currentCursorPosition = value;
    }

}
