//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CursorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CursorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CursorID" type="{http://www.opengis.net/ols/nav}CursorIDType"/>
 *         &lt;element name="CursorType" type="{http://www.opengis.net/ols/nav}CursorTypeEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CursorType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "cursorID",
    "cursorType"
})
public class CursorType {

    @XmlElement(name = "CursorID", required = true)
    protected CursorIDType cursorID;
    @XmlElement(name = "CursorType", required = true)
    protected CursorTypeEnum cursorType;

    /**
     * Gets the value of the cursorID property.
     * 
     * @return
     *     possible object is
     *     {@link CursorIDType }
     *     
     */
    public CursorIDType getCursorID() {
        return cursorID;
    }

    /**
     * Sets the value of the cursorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorIDType }
     *     
     */
    public void setCursorID(CursorIDType value) {
        this.cursorID = value;
    }

    /**
     * Gets the value of the cursorType property.
     * 
     * @return
     *     possible object is
     *     {@link CursorTypeEnum }
     *     
     */
    public CursorTypeEnum getCursorType() {
        return cursorType;
    }

    /**
     * Sets the value of the cursorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorTypeEnum }
     *     
     */
    public void setCursorType(CursorTypeEnum value) {
        this.cursorType = value;
    }

}
