//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DateTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{http://www.opengis.net/ols/nav}DateType" minOccurs="0"/>
 *         &lt;element name="EndDate" type="{http://www.opengis.net/ols/nav}DateType" minOccurs="0"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="TimeZone" type="{http://www.opengis.net/ols/nav}TimeZoneType" minOccurs="0"/>
 *         &lt;element name="DaylightSavingsTimeCode" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Exclusionary" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Spring" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Summer" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Fall" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Winter" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="Holiday" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DawnToDusk" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="DuskToDawn" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateTimeType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "startDate",
    "endDate",
    "startTime",
    "endTime",
    "timeZone",
    "daylightSavingsTimeCode"
})
public class DateTimeType {

    @XmlElement(name = "StartDate")
    protected DateType startDate;
    @XmlElement(name = "EndDate")
    protected DateType endDate;
    @XmlElement(name = "StartTime")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer startTime;
    @XmlElement(name = "EndTime")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer endTime;
    @XmlElement(name = "TimeZone")
    protected TimeZoneType timeZone;
    @XmlElement(name = "DaylightSavingsTimeCode")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer daylightSavingsTimeCode;
    @XmlAttribute(name = "Exclusionary")
    protected Boolean exclusionary;
    @XmlAttribute(name = "Spring")
    protected Boolean spring;
    @XmlAttribute(name = "Summer")
    protected Boolean summer;
    @XmlAttribute(name = "Fall")
    protected Boolean fall;
    @XmlAttribute(name = "Winter")
    protected Boolean winter;
    @XmlAttribute(name = "Holiday")
    protected Boolean holiday;
    @XmlAttribute(name = "DawnToDusk")
    protected Boolean dawnToDusk;
    @XmlAttribute(name = "DuskToDawn")
    protected Boolean duskToDawn;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setStartDate(DateType value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateType }
     *     
     */
    public DateType getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateType }
     *     
     */
    public void setEndDate(DateType value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartTime(Integer value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEndTime(Integer value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZoneType }
     *     
     */
    public TimeZoneType getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZoneType }
     *     
     */
    public void setTimeZone(TimeZoneType value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the daylightSavingsTimeCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaylightSavingsTimeCode() {
        return daylightSavingsTimeCode;
    }

    /**
     * Sets the value of the daylightSavingsTimeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaylightSavingsTimeCode(Integer value) {
        this.daylightSavingsTimeCode = value;
    }

    /**
     * Gets the value of the exclusionary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExclusionary() {
        if (exclusionary == null) {
            return false;
        } else {
            return exclusionary;
        }
    }

    /**
     * Sets the value of the exclusionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExclusionary(Boolean value) {
        this.exclusionary = value;
    }

    /**
     * Gets the value of the spring property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSpring() {
        return spring;
    }

    /**
     * Sets the value of the spring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSpring(Boolean value) {
        this.spring = value;
    }

    /**
     * Gets the value of the summer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSummer() {
        return summer;
    }

    /**
     * Sets the value of the summer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSummer(Boolean value) {
        this.summer = value;
    }

    /**
     * Gets the value of the fall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFall() {
        return fall;
    }

    /**
     * Sets the value of the fall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFall(Boolean value) {
        this.fall = value;
    }

    /**
     * Gets the value of the winter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWinter() {
        return winter;
    }

    /**
     * Sets the value of the winter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWinter(Boolean value) {
        this.winter = value;
    }

    /**
     * Gets the value of the holiday property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHoliday() {
        return holiday;
    }

    /**
     * Sets the value of the holiday property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHoliday(Boolean value) {
        this.holiday = value;
    }

    /**
     * Gets the value of the dawnToDusk property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDawnToDusk() {
        return dawnToDusk;
    }

    /**
     * Sets the value of the dawnToDusk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDawnToDusk(Boolean value) {
        this.dawnToDusk = value;
    }

    /**
     * Gets the value of the duskToDawn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDuskToDawn() {
        return duskToDawn;
    }

    /**
     * Sets the value of the duskToDawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDuskToDawn(Boolean value) {
        this.duskToDawn = value;
    }

}
