//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateTimeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DateTimeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MAP_DAY_OF_WEEK"/>
 *     &lt;enumeration value="MAP_ABSOLUTE_DATE"/>
 *     &lt;enumeration value="MAP_DAY_OF_YEAR"/>
 *     &lt;enumeration value="MAP_DAY_OF_MONTH"/>
 *     &lt;enumeration value="MAP_DAY_OF_WEEK_OF_MONTH"/>
 *     &lt;enumeration value="MAP_DAY_OF_WEEK_OF_YEAR"/>
 *     &lt;enumeration value="MAP_WEEK_OF_MONTH"/>
 *     &lt;enumeration value="MAP_WEEK_OF_YEAR"/>
 *     &lt;enumeration value="MAP_MONTH_OF_YEAR"/>
 *     &lt;enumeration value="MAP_DAY_OF_MONTH_OF_YEAR"/>
 *     &lt;enumeration value="MAP_DAY_OF_WEEK_OF_MONTH_OF_YEAR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DateTimeEnum", namespace = "http://www.opengis.net/ols/nav")
@XmlEnum
public enum DateTimeEnum {

    MAP_DAY_OF_WEEK,
    MAP_ABSOLUTE_DATE,
    MAP_DAY_OF_YEAR,
    MAP_DAY_OF_MONTH,
    MAP_DAY_OF_WEEK_OF_MONTH,
    MAP_DAY_OF_WEEK_OF_YEAR,
    MAP_WEEK_OF_MONTH,
    MAP_WEEK_OF_YEAR,
    MAP_MONTH_OF_YEAR,
    MAP_DAY_OF_MONTH_OF_YEAR,
    MAP_DAY_OF_WEEK_OF_MONTH_OF_YEAR;

    public String value() {
        return name();
    }

    public static DateTimeEnum fromValue(String v) {
        return valueOf(v);
    }

}
