//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DayOfWeekOfYearType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DayOfWeekOfYearType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DayOfWeek" type="{http://www.opengis.net/ols/nav}DayOfWeekEnum"/>
 *         &lt;element name="WeekOfYear" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DayOfWeekOfYearType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "dayOfWeek",
    "weekOfYear"
})
public class DayOfWeekOfYearType {

    @XmlElement(name = "DayOfWeek", required = true)
    protected DayOfWeekEnum dayOfWeek;
    @XmlElement(name = "WeekOfYear")
    @XmlSchemaType(name = "unsignedShort")
    protected int weekOfYear;

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfWeekEnum }
     *     
     */
    public DayOfWeekEnum getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfWeekEnum }
     *     
     */
    public void setDayOfWeek(DayOfWeekEnum value) {
        this.dayOfWeek = value;
    }

    /**
     * Gets the value of the weekOfYear property.
     * 
     */
    public int getWeekOfYear() {
        return weekOfYear;
    }

    /**
     * Sets the value of the weekOfYear property.
     * 
     */
    public void setWeekOfYear(int value) {
        this.weekOfYear = value;
    }

}
