//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ADT for a ProximityResponse. One or more POIs may be returned
 * 
 * <p>Java class for DirectoryResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectoryResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element name="POIContext" type="{http://www.opengis.net/xls}POIWithDistanceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectoryResponseType", propOrder = {
    "poiContext"
})
public class DirectoryResponseType
    extends AbstractResponseParametersType
{

    @XmlElement(name = "POIContext")
    protected List<POIWithDistanceType> poiContext;

    /**
     * Gets the value of the poiContext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poiContext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOIContext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link POIWithDistanceType }
     * 
     * 
     */
    public List<POIWithDistanceType> getPOIContext() {
        if (poiContext == null) {
            poiContext = new ArrayList<POIWithDistanceType>();
        }
        return this.poiContext;
    }

}
