//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EllipseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EllipseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractGeometricPrimitiveType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml}pos"/>
 *         &lt;element name="majorAxis" type="{http://www.opengis.net/gml}LengthType"/>
 *         &lt;element name="minorAxis" type="{http://www.opengis.net/gml}LengthType"/>
 *         &lt;element name="rotation" type="{http://www.opengis.net/gml}AngleType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EllipseType", propOrder = {
    "pos",
    "majorAxis",
    "minorAxis",
    "rotation"
})
public class EllipseType
    extends AbstractGeometricPrimitiveType
{

    @XmlElement(namespace = "http://www.opengis.net/gml", required = true)
    protected DirectPositionType pos;
    @XmlElement(required = true)
    protected LengthType majorAxis;
    @XmlElement(required = true)
    protected LengthType minorAxis;
    @XmlElement(required = true)
    protected AngleTypeNav rotation;

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link DirectPositionType }
     *     
     */
    public DirectPositionType getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectPositionType }
     *     
     */
    public void setPos(DirectPositionType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the majorAxis property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getMajorAxis() {
        return majorAxis;
    }

    /**
     * Sets the value of the majorAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setMajorAxis(LengthType value) {
        this.majorAxis = value;
    }

    /**
     * Gets the value of the minorAxis property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getMinorAxis() {
        return minorAxis;
    }

    /**
     * Sets the value of the minorAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setMinorAxis(LengthType value) {
        this.minorAxis = value;
    }

    /**
     * Gets the value of the rotation property.
     * 
     * @return
     *     possible object is
     *     {@link AngleTypeNav }
     *     
     */
    public AngleTypeNav getRotation() {
        return rotation;
    }

    /**
     * Sets the value of the rotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleTypeNav }
     *     
     */
    public void setRotation(AngleTypeNav value) {
        this.rotation = value;
    }

}
