//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtendedDateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedDateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DayOfWeek" type="{http://www.opengis.net/ols/nav}DayOfWeekEnum" minOccurs="0"/>
 *         &lt;element name="DayOfYear" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="DayOfMonth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="DayOfWeekOfMonthType" type="{http://www.opengis.net/ols/nav}DayOfWeekOfMonthType" minOccurs="0"/>
 *         &lt;element name="DayOfWeekOfYearType" type="{http://www.opengis.net/ols/nav}DayOfWeekOfYearType" minOccurs="0"/>
 *         &lt;element name="WeekOfMonth" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="WeekOfYear" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="MonthOfYear" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="DayOfMonthOfYearType" type="{http://www.opengis.net/ols/nav}DayOfMonthOfYearType" minOccurs="0"/>
 *         &lt;element name="DayOfWeekOfMonthOfYearType" type="{http://www.opengis.net/ols/nav}DayOfMonthOfYearType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedDateType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "dayOfWeek",
    "dayOfYear",
    "dayOfMonth",
    "dayOfWeekOfMonthType",
    "dayOfWeekOfYearType",
    "weekOfMonth",
    "weekOfYear",
    "monthOfYear",
    "dayOfMonthOfYearType",
    "dayOfWeekOfMonthOfYearType"
})
public class ExtendedDateType {

    @XmlElement(name = "DayOfWeek")
    protected DayOfWeekEnum dayOfWeek;
    @XmlElement(name = "DayOfYear")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer dayOfYear;
    @XmlElement(name = "DayOfMonth")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer dayOfMonth;
    @XmlElement(name = "DayOfWeekOfMonthType")
    protected DayOfWeekOfMonthType dayOfWeekOfMonthType;
    @XmlElement(name = "DayOfWeekOfYearType")
    protected DayOfWeekOfYearType dayOfWeekOfYearType;
    @XmlElement(name = "WeekOfMonth")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer weekOfMonth;
    @XmlElement(name = "WeekOfYear")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer weekOfYear;
    @XmlElement(name = "MonthOfYear")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer monthOfYear;
    @XmlElement(name = "DayOfMonthOfYearType")
    protected DayOfMonthOfYearType dayOfMonthOfYearType;
    @XmlElement(name = "DayOfWeekOfMonthOfYearType")
    protected DayOfMonthOfYearType dayOfWeekOfMonthOfYearType;

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfWeekEnum }
     *     
     */
    public DayOfWeekEnum getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfWeekEnum }
     *     
     */
    public void setDayOfWeek(DayOfWeekEnum value) {
        this.dayOfWeek = value;
    }

    /**
     * Gets the value of the dayOfYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDayOfYear() {
        return dayOfYear;
    }

    /**
     * Sets the value of the dayOfYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDayOfYear(Integer value) {
        this.dayOfYear = value;
    }

    /**
     * Gets the value of the dayOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDayOfMonth(Integer value) {
        this.dayOfMonth = value;
    }

    /**
     * Gets the value of the dayOfWeekOfMonthType property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfWeekOfMonthType }
     *     
     */
    public DayOfWeekOfMonthType getDayOfWeekOfMonthType() {
        return dayOfWeekOfMonthType;
    }

    /**
     * Sets the value of the dayOfWeekOfMonthType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfWeekOfMonthType }
     *     
     */
    public void setDayOfWeekOfMonthType(DayOfWeekOfMonthType value) {
        this.dayOfWeekOfMonthType = value;
    }

    /**
     * Gets the value of the dayOfWeekOfYearType property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfWeekOfYearType }
     *     
     */
    public DayOfWeekOfYearType getDayOfWeekOfYearType() {
        return dayOfWeekOfYearType;
    }

    /**
     * Sets the value of the dayOfWeekOfYearType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfWeekOfYearType }
     *     
     */
    public void setDayOfWeekOfYearType(DayOfWeekOfYearType value) {
        this.dayOfWeekOfYearType = value;
    }

    /**
     * Gets the value of the weekOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeekOfMonth() {
        return weekOfMonth;
    }

    /**
     * Sets the value of the weekOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeekOfMonth(Integer value) {
        this.weekOfMonth = value;
    }

    /**
     * Gets the value of the weekOfYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWeekOfYear() {
        return weekOfYear;
    }

    /**
     * Sets the value of the weekOfYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWeekOfYear(Integer value) {
        this.weekOfYear = value;
    }

    /**
     * Gets the value of the monthOfYear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMonthOfYear() {
        return monthOfYear;
    }

    /**
     * Sets the value of the monthOfYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMonthOfYear(Integer value) {
        this.monthOfYear = value;
    }

    /**
     * Gets the value of the dayOfMonthOfYearType property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfMonthOfYearType }
     *     
     */
    public DayOfMonthOfYearType getDayOfMonthOfYearType() {
        return dayOfMonthOfYearType;
    }

    /**
     * Sets the value of the dayOfMonthOfYearType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfMonthOfYearType }
     *     
     */
    public void setDayOfMonthOfYearType(DayOfMonthOfYearType value) {
        this.dayOfMonthOfYearType = value;
    }

    /**
     * Gets the value of the dayOfWeekOfMonthOfYearType property.
     * 
     * @return
     *     possible object is
     *     {@link DayOfMonthOfYearType }
     *     
     */
    public DayOfMonthOfYearType getDayOfWeekOfMonthOfYearType() {
        return dayOfWeekOfMonthOfYearType;
    }

    /**
     * Sets the value of the dayOfWeekOfMonthOfYearType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DayOfMonthOfYearType }
     *     
     */
    public void setDayOfWeekOfMonthOfYearType(DayOfMonthOfYearType value) {
        this.dayOfWeekOfMonthOfYearType = value;
    }

}
