//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FetchDirectionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FetchDirectionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FetchForward"/>
 *     &lt;enumeration value="FetchBackward"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FetchDirectionType", namespace = "http://www.opengis.net/ols/nav")
@XmlEnum
public enum FetchDirectionType {

    @XmlEnumValue("FetchForward")
    FETCH_FORWARD("FetchForward"),
    @XmlEnumValue("FetchBackward")
    FETCH_BACKWARD("FetchBackward");
    private final String value;

    FetchDirectionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FetchDirectionType fromValue(String v) {
        for (FetchDirectionType c: FetchDirectionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
