//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetCursorInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetCursorInfoResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element name="CursorInfo" type="{http://www.opengis.net/ols/nav}CursorInfoType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCursorInfoResponse", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "cursorInfo"
})
public class GetCursorInfoResponse
    extends AbstractResponseParametersType
{

    @XmlElement(name = "CursorInfo", required = true)
    protected CursorInfoType cursorInfo;

    /**
     * Gets the value of the cursorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CursorInfoType }
     *     
     */
    public CursorInfoType getCursorInfo() {
        return cursorInfo;
    }

    /**
     * Sets the value of the cursorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorInfoType }
     *     
     */
    public void setCursorInfo(CursorInfoType value) {
        this.cursorInfo = value;
    }

}
