//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetNearbyMapObjResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetNearbyMapObjResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element name="MapObj" type="{http://www.opengis.net/ols/nav}MapObjType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetNearbyMapObjResponseType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "mapObj"
})
public class GetNearbyMapObjResponseType
    extends AbstractResponseParametersType
{

    @XmlElement(name = "MapObj", required = true)
    protected MapObjType mapObj;

    /**
     * Gets the value of the mapObj property.
     * 
     * @return
     *     possible object is
     *     {@link MapObjType }
     *     
     */
    public MapObjType getMapObj() {
        return mapObj;
    }

    /**
     * Sets the value of the mapObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapObjType }
     *     
     */
    public void setMapObj(MapObjType value) {
        this.mapObj = value;
    }

}
