//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetNearbyMapObjRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetNearbyMapObjRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractRequestParametersType">
 *       &lt;sequence>
 *         &lt;element name="CurrentPosition" type="{http://www.opengis.net/xls}PositionType"/>
 *         &lt;element name="Delta" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="GetFirstBucket" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priority" use="required" type="{http://www.opengis.net/ols/nav}PriorityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetNearbyMapObjRequestType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "currentPosition",
    "delta",
    "getFirstBucket"
})
public class GetNearbyMapObjRequestType
    extends AbstractRequestParametersType
{

    @XmlElement(name = "CurrentPosition", required = true)
    protected PositionType currentPosition;
    @XmlElement(name = "Delta", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger delta;
    @XmlElement(name = "GetFirstBucket", defaultValue = "0")
    protected BigInteger getFirstBucket;
    @XmlAttribute(name = "priority", required = true)
    protected int priority;

    /**
     * Gets the value of the currentPosition property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getCurrentPosition() {
        return currentPosition;
    }

    /**
     * Sets the value of the currentPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setCurrentPosition(PositionType value) {
        this.currentPosition = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDelta(BigInteger value) {
        this.delta = value;
    }

    /**
     * Gets the value of the getFirstBucket property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGetFirstBucket() {
        return getFirstBucket;
    }

    /**
     * Sets the value of the getFirstBucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGetFirstBucket(BigInteger value) {
        this.getFirstBucket = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

}
