//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetPositionResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetPositionResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element name="Locus" type="{http://www.opengis.net/ols/nav}LocusType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetPositionResponseType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "locus"
})
public class GetPositionResponseType
    extends AbstractResponseParametersType
{

    @XmlElement(name = "Locus", required = true)
    protected LocusType locus;

    /**
     * Gets the value of the locus property.
     * 
     * @return
     *     possible object is
     *     {@link LocusType }
     *     
     */
    public LocusType getLocus() {
        return locus;
    }

    /**
     * Sets the value of the locus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocusType }
     *     
     */
    public void setLocus(LocusType value) {
        this.locus = value;
    }

}
