//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetPositionRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetPositionRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractRequestParametersType">
 *       &lt;sequence>
 *         &lt;element name="UseHistory" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CurrentPosition" type="{http://www.opengis.net/xls}PositionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priority" use="required" type="{http://www.opengis.net/ols/nav}PriorityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetPositionRequestType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "useHistory",
    "currentPosition"
})
public class GetPositionRequestType
    extends AbstractRequestParametersType
{

    @XmlElement(name = "UseHistory")
    protected boolean useHistory;
    @XmlElement(name = "CurrentPosition", required = true)
    protected PositionType currentPosition;
    @XmlAttribute(name = "priority", required = true)
    protected int priority;

    /**
     * Gets the value of the useHistory property.
     * 
     */
    public boolean isUseHistory() {
        return useHistory;
    }

    /**
     * Sets the value of the useHistory property.
     * 
     */
    public void setUseHistory(boolean value) {
        this.useHistory = value;
    }

    /**
     * Gets the value of the currentPosition property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getCurrentPosition() {
        return currentPosition;
    }

    /**
     * Sets the value of the currentPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setCurrentPosition(PositionType value) {
        this.currentPosition = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

}
