//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MapType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MapType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractDataType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Content" type="{http://www.opengis.net/xls}ContentType"/>
 *         &lt;choice>
 *           &lt;element name="BBoxContext" type="{http://www.opengis.net/gml}EnvelopeType"/>
 *           &lt;element name="CenterContext" type="{http://www.opengis.net/xls}CenterContextType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MapType", propOrder = {
    "content",
    "bBoxContext",
    "centerContext"
})
@XmlSeeAlso({
    RouteMapType.class
})
public class MapType
    extends AbstractDataType
{

    @XmlElement(name = "Content")
    protected ContentType content;
    @XmlElement(name = "BBoxContext")
    protected EnvelopeType bBoxContext;
    @XmlElement(name = "CenterContext")
    protected CenterContextType centerContext;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ContentType }
     *     
     */
    public ContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentType }
     *     
     */
    public void setContent(ContentType value) {
        this.content = value;
    }

    /**
     * Gets the value of the bBoxContext property.
     * 
     * @return
     *     possible object is
     *     {@link EnvelopeType }
     *     
     */
    public EnvelopeType getBBoxContext() {
        return bBoxContext;
    }

    /**
     * Sets the value of the bBoxContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvelopeType }
     *     
     */
    public void setBBoxContext(EnvelopeType value) {
        this.bBoxContext = value;
    }

    /**
     * Gets the value of the centerContext property.
     * 
     * @return
     *     possible object is
     *     {@link CenterContextType }
     *     
     */
    public CenterContextType getCenterContext() {
        return centerContext;
    }

    /**
     * Sets the value of the centerContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link CenterContextType }
     *     
     */
    public void setCenterContext(CenterContextType value) {
        this.centerContext = value;
    }

}
