//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NearestCriterionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NearestCriterionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Proximity"/>
 *     &lt;enumeration value="Fastest"/>
 *     &lt;enumeration value="Shortest"/>
 *     &lt;enumeration value="Easiest"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NearestCriterionType")
@XmlEnum
public enum NearestCriterionType {

    @XmlEnumValue("Proximity")
    PROXIMITY("Proximity"),
    @XmlEnumValue("Fastest")
    FASTEST("Fastest"),
    @XmlEnumValue("Shortest")
    SHORTEST("Shortest"),
    @XmlEnumValue("Easiest")
    EASIEST("Easiest");
    private final String value;

    NearestCriterionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NearestCriterionType fromValue(String v) {
        for (NearestCriterionType c: NearestCriterionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
