//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NullEnumeration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NullEnumeration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="inapplicable"/>
 *     &lt;enumeration value="missing"/>
 *     &lt;enumeration value="template"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="withheld"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NullEnumeration", namespace = "http://www.opengis.net/gml")
@XmlEnum
public enum NullEnumeration {

    @XmlEnumValue("inapplicable")
    INAPPLICABLE("inapplicable"),
    @XmlEnumValue("missing")
    MISSING("missing"),
    @XmlEnumValue("template")
    TEMPLATE("template"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("withheld")
    WITHHELD("withheld");
    private final String value;

    NullEnumeration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NullEnumeration fromValue(String v) {
        for (NullEnumeration c: NullEnumeration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
