//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputGatewayParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputGatewayParametersType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractGatewayParametersType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}OutputMSIDs"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputGatewayParametersType", propOrder = {
    "outputMSIDs"
})
public class OutputGatewayParametersType
    extends AbstractGatewayParametersType
{

    @XmlElement(name = "OutputMSIDs", required = true)
    protected OutputMSIDsType outputMSIDs;

    /**
     * Gets the value of the outputMSIDs property.
     * 
     * @return
     *     possible object is
     *     {@link OutputMSIDsType }
     *     
     */
    public OutputMSIDsType getOutputMSIDs() {
        return outputMSIDs;
    }

    /**
     * Sets the value of the outputMSIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputMSIDsType }
     *     
     */
    public void setOutputMSIDs(OutputMSIDsType value) {
        this.outputMSIDs = value;
    }

}
