//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutputMSIDsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutputMSIDsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractMSIDsType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}OutputMSInformation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutputMSIDsType", propOrder = {
    "outputMSInformation"
})
public class OutputMSIDsType
    extends AbstractMSIDsType
{

    @XmlElement(name = "OutputMSInformation", required = true)
    protected OutputMSInformationType outputMSInformation;

    /**
     * Gets the value of the outputMSInformation property.
     * 
     * @return
     *     possible object is
     *     {@link OutputMSInformationType }
     *     
     */
    public OutputMSInformationType getOutputMSInformation() {
        return outputMSInformation;
    }

    /**
     * Sets the value of the outputMSInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputMSInformationType }
     *     
     */
    public void setOutputMSInformation(OutputMSInformationType value) {
        this.outputMSInformation = value;
    }

}
