//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines POI selection criteria as a list of properties
 * 
 * <p>Java class for POIPropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POIPropertiesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractPOISelectionCriteriaType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}_POIProperty" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="directoryType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POIPropertiesType", propOrder = {
    "poiProperty"
})
@XmlSeeAlso({
    POIProperties.class
})
public class POIPropertiesType
    extends AbstractPOISelectionCriteriaType
{

    @XmlElementRef(name = "_POIProperty", namespace = "http://www.opengis.net/xls", type = JAXBElement.class)
    protected List<JAXBElement<?>> poiProperty;
    @XmlAttribute(name = "directoryType")
    protected String directoryType;

    /**
     * Gets the value of the poiProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poiProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPOIProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link POIPropertyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getPOIProperty() {
        if (poiProperty == null) {
            poiProperty = new ArrayList<JAXBElement<?>>();
        }
        return this.poiProperty;
    }

    /**
     * Gets the value of the directoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectoryType() {
        return directoryType;
    }

    /**
     * Sets the value of the directoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectoryType(String value) {
        this.directoryType = value;
    }

}
