//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This request is for the server to process all of the records in the result set starting with the first record regardless of where the cursor's current position is currently positioned. Upon completion of this request, the cursor current position is positioned at the end of the complete result set.
 * The action function's first parameter is a pointer to a structure of the type contained in the cursor's records.  The second is an application-defined structure, or NULL. In processing each cursor element, the third element  of ProcessCursorRequest is passed in as the second argument of ActionFunc.  If ActionFunc yields a negative result value, processing will be aborted.
 * ProcessCursorResponse returns the number of records processed.
 * 
 * <p>Java class for ProcessCursorRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessCursorRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractRequestParametersType">
 *       &lt;sequence>
 *         &lt;element name="CursorID" type="{http://www.opengis.net/ols/nav}CursorIDType"/>
 *         &lt;element name="ActionFunc" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="ActionFuncParam" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priority" use="required" type="{http://www.opengis.net/ols/nav}PriorityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessCursorRequest", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "cursorID",
    "actionFunc",
    "actionFuncParam"
})
public class ProcessCursorRequest
    extends AbstractRequestParametersType
{

    @XmlElement(name = "CursorID", required = true)
    protected CursorIDType cursorID;
    @XmlElement(name = "ActionFunc", required = true)
    protected Object actionFunc;
    @XmlElement(name = "ActionFuncParam", required = true)
    protected Object actionFuncParam;
    @XmlAttribute(name = "priority", required = true)
    protected int priority;

    /**
     * Gets the value of the cursorID property.
     * 
     * @return
     *     possible object is
     *     {@link CursorIDType }
     *     
     */
    public CursorIDType getCursorID() {
        return cursorID;
    }

    /**
     * Sets the value of the cursorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorIDType }
     *     
     */
    public void setCursorID(CursorIDType value) {
        this.cursorID = value;
    }

    /**
     * Gets the value of the actionFunc property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getActionFunc() {
        return actionFunc;
    }

    /**
     * Sets the value of the actionFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setActionFunc(Object value) {
        this.actionFunc = value;
    }

    /**
     * Gets the value of the actionFuncParam property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getActionFuncParam() {
        return actionFuncParam;
    }

    /**
     * Sets the value of the actionFuncParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setActionFuncParam(Object value) {
        this.actionFuncParam = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

}
