//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessCursorResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessCursorResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element name="NumRecordsProcessed" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessCursorResponse", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "numRecordsProcessed"
})
public class ProcessCursorResponse
    extends AbstractResponseParametersType
{

    @XmlElement(name = "NumRecordsProcessed")
    protected long numRecordsProcessed;

    /**
     * Gets the value of the numRecordsProcessed property.
     * 
     */
    public long getNumRecordsProcessed() {
        return numRecordsProcessed;
    }

    /**
     * Sets the value of the numRecordsProcessed property.
     * 
     */
    public void setNumRecordsProcessed(long value) {
        this.numRecordsProcessed = value;
    }

}
