//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceSystemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferenceSystemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}_NamedReferenceSystem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceSystemType", propOrder = {
    "namedReferenceSystem"
})
public class ReferenceSystemType {

    @XmlElementRef(name = "_NamedReferenceSystem", namespace = "http://www.opengis.net/xls", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractNamedReferenceSystem>> namedReferenceSystem;

    /**
     * Gets the value of the namedReferenceSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namedReferenceSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamedReferenceSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NACEType }{@code >}
     * {@link JAXBElement }{@code <}{@link SICType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractNamedReferenceSystem }{@code >}
     * {@link JAXBElement }{@code <}{@link NAICSType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractNamedReferenceSystem>> getNamedReferenceSystem() {
        if (namedReferenceSystem == null) {
            namedReferenceSystem = new ArrayList<JAXBElement<? extends AbstractNamedReferenceSystem>>();
        }
        return this.namedReferenceSystem;
    }

}
