//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Reverse Geocode Request.
 * 
 * <p>Java class for ReverseGeocodeRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReverseGeocodeRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractRequestParametersType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}Position"/>
 *         &lt;element ref="{http://www.opengis.net/xls}ReverseGeocodePreference" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReverseGeocodeRequestType", propOrder = {
    "position",
    "reverseGeocodePreference"
})
public class ReverseGeocodeRequestType
    extends AbstractRequestParametersType
{

    @XmlElement(name = "Position", required = true)
    protected PositionType position;
    @XmlElement(name = "ReverseGeocodePreference")
    protected List<ReverseGeocodePreferenceType> reverseGeocodePreference;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link PositionType }
     *     
     */
    public PositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionType }
     *     
     */
    public void setPosition(PositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the reverseGeocodePreference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reverseGeocodePreference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReverseGeocodePreference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReverseGeocodePreferenceType }
     * 
     * 
     */
    public List<ReverseGeocodePreferenceType> getReverseGeocodePreference() {
        if (reverseGeocodePreference == null) {
            reverseGeocodePreference = new ArrayList<ReverseGeocodePreferenceType>();
        }
        return this.reverseGeocodePreference;
    }

}
