//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteHighwayUsageEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteHighwayUsageEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PROHIBIT_HIGHWAYS"/>
 *     &lt;enumeration value="AVOID_HIGHWAYS"/>
 *     &lt;enumeration value="PREFER_HIGHWAYS"/>
 *     &lt;enumeration value="NO_PREFERENCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteHighwayUsageEnum", namespace = "http://www.opengis.net/ols/nav")
@XmlEnum
public enum RouteHighwayUsageEnum {

    PROHIBIT_HIGHWAYS,
    AVOID_HIGHWAYS,
    PREFER_HIGHWAYS,
    NO_PREFERENCE;

    public String value() {
        return name();
    }

    public static RouteHighwayUsageEnum fromValue(String v) {
        return valueOf(v);
    }

}
