//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoutePreferenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoutePreferenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Fastest"/>
 *     &lt;enumeration value="Shortest"/>
 *     &lt;enumeration value="Pedestrian"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoutePreferenceType")
@XmlEnum
public enum RoutePreferenceType {


    /**
     * Minimize the travel time by vehicle.
     * 
     */
    @XmlEnumValue("Fastest")
    FASTEST("Fastest"),

    /**
     * Minimize the travel distance by vehicle.
     * 
     */
    @XmlEnumValue("Shortest")
    SHORTEST("Shortest"),

    /**
     * Best route by foot.
     * 
     */
    @XmlEnumValue("Pedestrian")
    PEDESTRIAN("Pedestrian");
    private final String value;

    RoutePreferenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoutePreferenceType fromValue(String v) {
        for (RoutePreferenceType c: RoutePreferenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
