//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteMapStyleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteMapStyleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Overview"/>
 *     &lt;enumeration value="Maneuver"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteMapStyleType")
@XmlEnum
public enum RouteMapStyleType {


    /**
     * Used to describe the map showing the full route
     * 
     */
    @XmlEnumValue("Overview")
    OVERVIEW("Overview"),

    /**
     * Used to describe the map showing a particular maneuver (often the maneuver corresponds to a single instruction)
     * 
     */
    @XmlEnumValue("Maneuver")
    MANEUVER("Maneuver");
    private final String value;

    RouteMapStyleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouteMapStyleType fromValue(String v) {
        for (RouteMapStyleType c: RouteMapStyleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
