//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This structure contains information about the cost criteria. It contains information about how to assign "exchange rate" cost to:
 * -- Road distance
 * -- Road travel time
 * -- Highway usage preference
 * -- Toll road usage preference
 * -- Scenic route preference
 * 
 * <p>Java class for RouteCostModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteCostModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinimizerGoal" type="{http://www.opengis.net/ols/nav}RouteMinimizeOptionEnum"/>
 *         &lt;element name="HighwayAffinity" type="{http://www.opengis.net/ols/nav}RouteHighwayUsageEnum" minOccurs="0"/>
 *         &lt;element name="TollroadAffinity" type="{http://www.opengis.net/ols/nav}RouteTollUsageEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ScenicRoute" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteCostModelType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "minimizerGoal",
    "highwayAffinity",
    "tollroadAffinity"
})
public class RouteCostModelType {

    @XmlElement(name = "MinimizerGoal", required = true)
    protected RouteMinimizeOptionEnum minimizerGoal;
    @XmlElement(name = "HighwayAffinity")
    protected RouteHighwayUsageEnum highwayAffinity;
    @XmlElement(name = "TollroadAffinity")
    protected RouteTollUsageEnum tollroadAffinity;
    @XmlAttribute(name = "ScenicRoute")
    protected Boolean scenicRoute;

    /**
     * Gets the value of the minimizerGoal property.
     * 
     * @return
     *     possible object is
     *     {@link RouteMinimizeOptionEnum }
     *     
     */
    public RouteMinimizeOptionEnum getMinimizerGoal() {
        return minimizerGoal;
    }

    /**
     * Sets the value of the minimizerGoal property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteMinimizeOptionEnum }
     *     
     */
    public void setMinimizerGoal(RouteMinimizeOptionEnum value) {
        this.minimizerGoal = value;
    }

    /**
     * Gets the value of the highwayAffinity property.
     * 
     * @return
     *     possible object is
     *     {@link RouteHighwayUsageEnum }
     *     
     */
    public RouteHighwayUsageEnum getHighwayAffinity() {
        return highwayAffinity;
    }

    /**
     * Sets the value of the highwayAffinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteHighwayUsageEnum }
     *     
     */
    public void setHighwayAffinity(RouteHighwayUsageEnum value) {
        this.highwayAffinity = value;
    }

    /**
     * Gets the value of the tollroadAffinity property.
     * 
     * @return
     *     possible object is
     *     {@link RouteTollUsageEnum }
     *     
     */
    public RouteTollUsageEnum getTollroadAffinity() {
        return tollroadAffinity;
    }

    /**
     * Sets the value of the tollroadAffinity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteTollUsageEnum }
     *     
     */
    public void setTollroadAffinity(RouteTollUsageEnum value) {
        this.tollroadAffinity = value;
    }

    /**
     * Gets the value of the scenicRoute property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isScenicRoute() {
        return scenicRoute;
    }

    /**
     * Sets the value of the scenicRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setScenicRoute(Boolean value) {
        this.scenicRoute = value;
    }

}
