//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This structure contains the criteria to be used by the DetermineRoute request: 
 * The cost criteria includes the following information:
 * -- Should travel time or travel distance be minimized?
 * -- Should highways be used?
 * -- Should toll roads be used?
 * -- Should a scenic route be preferred?
 * 	For which vehicle type(s)?
 * 	For what starting time?
 * 
 * <p>Java class for RouteControlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteControlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CostCriteria" type="{http://www.opengis.net/ols/nav}RouteCostModelType"/>
 *         &lt;element name="Vehicle" type="{http://www.opengis.net/ols/nav}VehicleType.N" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VehicleCompositionLogic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AND"/>
 *               &lt;enumeration value="OR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RouteStartDateTime" type="{http://www.opengis.net/ols/nav}DateTimeType" minOccurs="0"/>
 *         &lt;element name="RouteEndDateTime" type="{http://www.opengis.net/ols/nav}DateTimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="useRealTimeTraffic" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteControlType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "costCriteria",
    "vehicle",
    "vehicleCompositionLogic",
    "routeStartDateTime",
    "routeEndDateTime"
})
public class RouteControlType {

    @XmlElement(name = "CostCriteria", required = true)
    protected RouteCostModelType costCriteria;
    @XmlElement(name = "Vehicle")
    protected List<VehicleTypeN> vehicle;
    @XmlElement(name = "VehicleCompositionLogic")
    protected String vehicleCompositionLogic;
    @XmlElement(name = "RouteStartDateTime")
    protected DateTimeType routeStartDateTime;
    @XmlElement(name = "RouteEndDateTime")
    protected DateTimeType routeEndDateTime;
    @XmlAttribute(name = "useRealTimeTraffic")
    protected Boolean useRealTimeTraffic;

    /**
     * Gets the value of the costCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link RouteCostModelType }
     *     
     */
    public RouteCostModelType getCostCriteria() {
        return costCriteria;
    }

    /**
     * Sets the value of the costCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteCostModelType }
     *     
     */
    public void setCostCriteria(RouteCostModelType value) {
        this.costCriteria = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehicleTypeN }
     * 
     * 
     */
    public List<VehicleTypeN> getVehicle() {
        if (vehicle == null) {
            vehicle = new ArrayList<VehicleTypeN>();
        }
        return this.vehicle;
    }

    /**
     * Gets the value of the vehicleCompositionLogic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleCompositionLogic() {
        return vehicleCompositionLogic;
    }

    /**
     * Sets the value of the vehicleCompositionLogic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleCompositionLogic(String value) {
        this.vehicleCompositionLogic = value;
    }

    /**
     * Gets the value of the routeStartDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getRouteStartDateTime() {
        return routeStartDateTime;
    }

    /**
     * Sets the value of the routeStartDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setRouteStartDateTime(DateTimeType value) {
        this.routeStartDateTime = value;
    }

    /**
     * Gets the value of the routeEndDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeType }
     *     
     */
    public DateTimeType getRouteEndDateTime() {
        return routeEndDateTime;
    }

    /**
     * Sets the value of the routeEndDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeType }
     *     
     */
    public void setRouteEndDateTime(DateTimeType value) {
        this.routeEndDateTime = value;
    }

    /**
     * Gets the value of the useRealTimeTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseRealTimeTraffic() {
        if (useRealTimeTraffic == null) {
            return false;
        } else {
            return useRealTimeTraffic;
        }
    }

    /**
     * Sets the value of the useRealTimeTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseRealTimeTraffic(Boolean value) {
        this.useRealTimeTraffic = value;
    }

}
