//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Defines the criteria upon which a route is determined.
 * 
 * <p>Java class for RoutePlanType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutePlanType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}RoutePreference"/>
 *         &lt;element ref="{http://www.opengis.net/xls}WayPointList"/>
 *         &lt;element ref="{http://www.opengis.net/xls}AvoidList" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="useRealTimeTraffic" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="expectedStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="expectedEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutePlanType", propOrder = {
    "routePreference",
    "wayPointList",
    "avoidList"
})
public class RoutePlanType {

    @XmlElement(name = "RoutePreference", required = true)
    protected RoutePreferenceType routePreference;
    @XmlElement(name = "WayPointList", required = true)
    protected WayPointListType wayPointList;
    @XmlElement(name = "AvoidList")
    protected AvoidListType avoidList;
    @XmlAttribute(name = "useRealTimeTraffic")
    protected Boolean useRealTimeTraffic;
    @XmlAttribute(name = "expectedStartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedStartTime;
    @XmlAttribute(name = "expectedEndTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expectedEndTime;

    /**
     * Gets the value of the routePreference property.
     * 
     * @return
     *     possible object is
     *     {@link RoutePreferenceType }
     *     
     */
    public RoutePreferenceType getRoutePreference() {
        return routePreference;
    }

    /**
     * Sets the value of the routePreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutePreferenceType }
     *     
     */
    public void setRoutePreference(RoutePreferenceType value) {
        this.routePreference = value;
    }

    /**
     * Gets the value of the wayPointList property.
     * 
     * @return
     *     possible object is
     *     {@link WayPointListType }
     *     
     */
    public WayPointListType getWayPointList() {
        return wayPointList;
    }

    /**
     * Sets the value of the wayPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayPointListType }
     *     
     */
    public void setWayPointList(WayPointListType value) {
        this.wayPointList = value;
    }

    /**
     * Gets the value of the avoidList property.
     * 
     * @return
     *     possible object is
     *     {@link AvoidListType }
     *     
     */
    public AvoidListType getAvoidList() {
        return avoidList;
    }

    /**
     * Sets the value of the avoidList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvoidListType }
     *     
     */
    public void setAvoidList(AvoidListType value) {
        this.avoidList = value;
    }

    /**
     * Gets the value of the useRealTimeTraffic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseRealTimeTraffic() {
        if (useRealTimeTraffic == null) {
            return false;
        } else {
            return useRealTimeTraffic;
        }
    }

    /**
     * Sets the value of the useRealTimeTraffic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseRealTimeTraffic(Boolean value) {
        this.useRealTimeTraffic = value;
    }

    /**
     * Gets the value of the expectedStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedStartTime() {
        return expectedStartTime;
    }

    /**
     * Sets the value of the expectedStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedStartTime(XMLGregorianCalendar value) {
        this.expectedStartTime = value;
    }

    /**
     * Gets the value of the expectedEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedEndTime() {
        return expectedEndTime;
    }

    /**
     * Sets the value of the expectedEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedEndTime(XMLGregorianCalendar value) {
        this.expectedEndTime = value;
    }

}
