//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.29 at 06:46:24 PM CET 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * contains a set of link loci  associated with a single route point.
 * 
 * <p>Java class for RoutePointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutePointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LinkLoci" type="{http://www.opengis.net/ols/nav}LocusType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutePointType", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "linkLoci"
})
@XmlSeeAlso({
    org.jvnet.ogc.RoutePointSequenceType.ViaPoint.class
})
public class RoutePointType {

    @XmlElement(name = "LinkLoci", required = true)
    protected List<LocusType> linkLoci;

    /**
     * Gets the value of the linkLoci property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkLoci property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkLoci().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocusType }
     * 
     * 
     */
    public List<LocusType> getLinkLoci() {
        if (linkLoci == null) {
            linkLoci = new ArrayList<LocusType>();
        }
        return this.linkLoci;
    }

}
