//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This request positions a large result set cursor current position (CP) to a specified record within the complete result set. The action of this request  can be described in two steps as follows, although there is no implication that the actual implementation of the request must be implemented in this way: First, if the "CursorStartPosition" element is RESULT_SET_START, the CP is moved to the gap before the first record; if the "CursorStartPosition" element is RESULT_SET_END, the CP is moved to the gap after the last record; and if the "CursorStartPosition" element is CURRENT_POSITION, the CP is not moved.  Second, if NumOfPositions is positive, the CP is moved forward (toward the end of the result set) by NumOfPositions records; if NumOfPositions is negative, the CP is moved backward (toward the beginning of the result set) by NumOfPositions records; if NumOfPositions is zero, the CP is not moved.  However, if this movement would move the CP before the gap at the beginning of the large result set  or after the gap at the end of the large result set, the CP is instead left at that gap.
 * 
 * 
 * <p>Java class for SetCursorPositionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SetCursorPositionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractRequestParametersType">
 *       &lt;sequence>
 *         &lt;element name="CursorID" type="{http://www.opengis.net/ols/nav}CursorIDType"/>
 *         &lt;element name="CursorStartPosition" type="{http://www.opengis.net/ols/nav}CursorOriginEnum"/>
 *         &lt;element name="NumOfPositions" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *       &lt;attribute name="priority" use="required" type="{http://www.opengis.net/ols/nav}PriorityType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetCursorPositionRequest", namespace = "http://www.opengis.net/ols/nav", propOrder = {
    "cursorID",
    "cursorStartPosition",
    "numOfPositions"
})
public class SetCursorPositionRequest
    extends AbstractRequestParametersType
{

    @XmlElement(name = "CursorID", required = true)
    protected CursorIDType cursorID;
    @XmlElement(name = "CursorStartPosition", required = true)
    protected CursorOriginEnum cursorStartPosition;
    @XmlElement(name = "NumOfPositions", defaultValue = "0")
    protected long numOfPositions;
    @XmlAttribute(name = "priority", required = true)
    protected int priority;

    /**
     * Gets the value of the cursorID property.
     * 
     * @return
     *     possible object is
     *     {@link CursorIDType }
     *     
     */
    public CursorIDType getCursorID() {
        return cursorID;
    }

    /**
     * Sets the value of the cursorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorIDType }
     *     
     */
    public void setCursorID(CursorIDType value) {
        this.cursorID = value;
    }

    /**
     * Gets the value of the cursorStartPosition property.
     * 
     * @return
     *     possible object is
     *     {@link CursorOriginEnum }
     *     
     */
    public CursorOriginEnum getCursorStartPosition() {
        return cursorStartPosition;
    }

    /**
     * Sets the value of the cursorStartPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CursorOriginEnum }
     *     
     */
    public void setCursorStartPosition(CursorOriginEnum value) {
        this.cursorStartPosition = value;
    }

    /**
     * Gets the value of the numOfPositions property.
     * 
     */
    public long getNumOfPositions() {
        return numOfPositions;
    }

    /**
     * Sets the value of the numOfPositions property.
     * 
     */
    public void setNumOfPositions(long value) {
        this.numOfPositions = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     */
    public int getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     */
    public void setPriority(int value) {
        this.priority = value;
    }

}
