//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SLIAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SLIAType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/xls}AbstractResponseParametersType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}OutputGatewayParameters"/>
 *       &lt;/sequence>
 *       &lt;attribute name="requestID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SLIAType", propOrder = {
    "outputGatewayParameters"
})
public class SLIAType
    extends AbstractResponseParametersType
{

    @XmlElement(name = "OutputGatewayParameters", required = true)
    protected OutputGatewayParametersType outputGatewayParameters;
    @XmlAttribute(name = "requestID")
    protected String requestID;

    /**
     * Gets the value of the outputGatewayParameters property.
     * 
     * @return
     *     possible object is
     *     {@link OutputGatewayParametersType }
     *     
     */
    public OutputGatewayParametersType getOutputGatewayParameters() {
        return outputGatewayParameters;
    }

    /**
     * Sets the value of the outputGatewayParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputGatewayParametersType }
     *     
     */
    public void setOutputGatewayParameters(OutputGatewayParametersType value) {
        this.outputGatewayParameters = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

}
