//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines a list of waypoints along a route.
 * 
 * <p>Java class for WayPointListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WayPointListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}StartPoint"/>
 *         &lt;element ref="{http://www.opengis.net/xls}ViaPoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/xls}EndPoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WayPointListType", propOrder = {
    "startPoint",
    "viaPoint",
    "endPoint"
})
public class WayPointListType {

    @XmlElement(name = "StartPoint", required = true)
    protected WayPointType startPoint;
    @XmlElement(name = "ViaPoint")
    protected List<WayPointType> viaPoint;
    @XmlElement(name = "EndPoint", required = true)
    protected WayPointType endPoint;

    /**
     * Gets the value of the startPoint property.
     * 
     * @return
     *     possible object is
     *     {@link WayPointType }
     *     
     */
    public WayPointType getStartPoint() {
        return startPoint;
    }

    /**
     * Sets the value of the startPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayPointType }
     *     
     */
    public void setStartPoint(WayPointType value) {
        this.startPoint = value;
    }

    /**
     * Gets the value of the viaPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viaPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViaPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WayPointType }
     * 
     * 
     */
    public List<WayPointType> getViaPoint() {
        if (viaPoint == null) {
            viaPoint = new ArrayList<WayPointType>();
        }
        return this.viaPoint;
    }

    /**
     * Gets the value of the endPoint property.
     * 
     * @return
     *     possible object is
     *     {@link WayPointType }
     *     
     */
    public WayPointType getEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link WayPointType }
     *     
     */
    public void setEndPoint(WayPointType value) {
        this.endPoint = value;
    }

}
