//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.22 at 11:01:13 AM CEST 
//


package org.jvnet.ogc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines a spatial filter which selects POIs located within a specified bounding area.
 * 
 * <p>Java class for WithinBoundaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WithinBoundaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/xls}AOI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WithinBoundaryType", propOrder = {
    "aoi"
})
public class WithinBoundaryType {

    @XmlElement(name = "AOI", required = true)
    protected AreaOfInterestType aoi;

    /**
     * Gets the value of the aoi property.
     * 
     * @return
     *     possible object is
     *     {@link AreaOfInterestType }
     *     
     */
    public AreaOfInterestType getAOI() {
        return aoi;
    }

    /**
     * Sets the value of the aoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AreaOfInterestType }
     *     
     */
    public void setAOI(AreaOfInterestType value) {
        this.aoi = value;
    }

}
